## name: Dark Magic
# author: David Morais (https://github.com/davidsmorais)
# variant: "dark"
background              #0f0f17
foreground              #bbccee
selection_foreground    #e8f0ff
selection_background    #22222e
cursor                  #e8f0ff
cursor_text_color       #0f0f17
active_tab_foreground   #0f0f17
active_tab_background   #66eeaa
inactive_tab_foreground #6b6b89
inactive_tab_background #17171f
active_border_color     #66eeaa

# normal colors
color0  #0f0f17
color1  #bb324c
color2  #b4f09e
color3  #fbde66
color4  #6bc7f5
color5  #cfa3f5
color6  #66eeaa
color7  #bbccee

# bright colors
color8  #424260
color9  #ff385e
color10 #00ffab
color11 #ffd31b
color12 #38daff
color13 #db6797
color14 #52f3f3
color15 #e8f0ff
